const byId = (id) => document.getElementById(id);

export const elements = {
  portalAdminTab: byId("portalAdminTab"),
  portalEssTab: byId("portalEssTab"),
  portalFeedback: byId("portalFeedback"),
  portalModeLabel: byId("portalModeLabel"),
  screenTitle: byId("screenTitle"),
  screenSubtitle: byId("screenSubtitle"),
  criticalRule: byId("criticalRule"),

  navGroups: [...document.querySelectorAll("[data-nav-portal]")],
  navButtons: [...document.querySelectorAll("[data-screen-target]")],
  screens: [...document.querySelectorAll("[data-screen]")],

  metricClients: byId("metricClients"),
  metricProjects: byId("metricProjects"),
  metricPending: byId("metricPending"),
  metricPayrollRuns: byId("metricPayrollRuns"),
  metricApprovedHours: byId("metricApprovedHours"),
  metricOtHours: byId("metricOtHours"),
  countryMixBody: byId("countryMixBody"),
  projectHealthBody: byId("projectHealthBody"),

  clientForm: byId("clientForm"),
  clientName: byId("clientName"),
  clientCountry: byId("clientCountry"),
  clientCurrency: byId("clientCurrency"),
  clientGstNumber: byId("clientGstNumber"),
  clientsBody: byId("clientsBody"),

  rateCardForm: byId("rateCardForm"),
  rateCardName: byId("rateCardName"),
  rateCardRole: byId("rateCardRole"),
  rateCardCountry: byId("rateCardCountry"),
  rateCardCurrency: byId("rateCardCurrency"),
  rateCardHourlyRate: byId("rateCardHourlyRate"),
  rateCardDailyShift: byId("rateCardDailyShift"),
  rateCardWeeklyLimit: byId("rateCardWeeklyLimit"),
  rateCardBiweeklyLimit: byId("rateCardBiweeklyLimit"),
  rateCardMonthlyLimit: byId("rateCardMonthlyLimit"),
  rateCardOtFrequency: byId("rateCardOtFrequency"),
  rateCardOtThreshold: byId("rateCardOtThreshold"),
  rateCardOtMultiplier: byId("rateCardOtMultiplier"),
  rateCardOpenBucket: byId("rateCardOpenBucket"),
  rateCardsBody: byId("rateCardsBody"),

  projectForm: byId("projectForm"),
  projectClient: byId("projectClient"),
  projectName: byId("projectName"),
  projectType: byId("projectType"),
  projectRateCard: byId("projectRateCard"),
  projectPayPeriod: byId("projectPayPeriod"),
  projectEstimatedHours: byId("projectEstimatedHours"),
  projectStartDate: byId("projectStartDate"),
  projectEndDate: byId("projectEndDate"),
  projectTaskPolicy: byId("projectTaskPolicy"),
  projectEstimatePolicy: byId("projectEstimatePolicy"),
  projectAssignees: byId("projectAssignees"),
  projectsBody: byId("projectsBody"),

  taskForm: byId("taskForm"),
  taskProject: byId("taskProject"),
  taskName: byId("taskName"),
  taskStartDate: byId("taskStartDate"),
  taskEndDate: byId("taskEndDate"),
  taskDueDate: byId("taskDueDate"),
  taskEstimatedHours: byId("taskEstimatedHours"),
  tasksBody: byId("tasksBody"),

  adminTimesheetsList: byId("adminTimesheetsList"),
  approvalsList: byId("approvalsList"),
  approvalBulkReason: byId("approvalBulkReason"),
  approveSelectedButton: byId("approveSelectedButton"),
  rejectSelectedButton: byId("rejectSelectedButton"),

  payrollRunForm: byId("payrollRunForm"),
  payrollWorker: byId("payrollWorker"),
  payrollProject: byId("payrollProject"),
  payrollScope: byId("payrollScope"),
  payrollPreview: byId("payrollPreview"),
  payrollRunsBody: byId("payrollRunsBody"),

  settingsForm: byId("settingsForm"),
  settingsCountry: byId("settingsCountry"),
  settingsDailyShift: byId("settingsDailyShift"),
  settingsWeeklyLimit: byId("settingsWeeklyLimit"),
  settingsBiweeklyLimit: byId("settingsBiweeklyLimit"),
  settingsMonthlyLimit: byId("settingsMonthlyLimit"),
  settingsOtFrequency: byId("settingsOtFrequency"),
  settingsOtThreshold: byId("settingsOtThreshold"),
  settingsOtMultiplier: byId("settingsOtMultiplier"),
  settingsOpenBucket: byId("settingsOpenBucket"),
  settingsBasicPercent: byId("settingsBasicPercent"),
  settingsPfRate: byId("settingsPfRate"),
  settingsEsiRate: byId("settingsEsiRate"),
  settingsEsiThreshold: byId("settingsEsiThreshold"),
  settingsProfessionalTax: byId("settingsProfessionalTax"),
  settingsTdsRate: byId("settingsTdsRate"),
  settingsFederalTaxRate: byId("settingsFederalTaxRate"),
  settingsStateTaxRate: byId("settingsStateTaxRate"),
  settingsSocialSecurityRate: byId("settingsSocialSecurityRate"),
  settingsMedicareRate: byId("settingsMedicareRate"),
  permissionsBody: byId("permissionsBody"),
  notificationsList: byId("notificationsList"),
  auditList: byId("auditList"),

  essWorker: byId("essWorker"),
  essProject: byId("essProject"),
  essTask: byId("essTask"),
  essDate: byId("essDate"),
  essLoggedHours: byId("essLoggedHours"),
  essBreakMinutes: byId("essBreakMinutes"),
  essCategory: byId("essCategory"),
  essNotes: byId("essNotes"),
  essLogForm: byId("essLogForm"),
  essEntriesBody: byId("essEntriesBody"),
  essDraftCount: byId("essDraftCount"),
  essSubmittedCount: byId("essSubmittedCount"),
  essApprovedCount: byId("essApprovedCount"),
  essNetPreview: byId("essNetPreview"),
  essDraftGroups: byId("essDraftGroups"),
  essSubmitForm: byId("essSubmitForm"),
  essSubmitWorker: byId("essSubmitWorker"),
  essSubmitProject: byId("essSubmitProject"),
  essSubmitScope: byId("essSubmitScope"),
  essTimesheetsList: byId("essTimesheetsList"),
  essStatusFeed: byId("essStatusFeed"),

  agentForm: byId("agentForm"),
  agentInput: byId("agentInput"),
  agentMessages: byId("agentMessages"),
  agentHintButtons: [...document.querySelectorAll("[data-agent-prompt]")],
};
