/**
 * Sample data to render salary slip templates in preview mode.
 * This fills Handlebars variables with realistic dummy values.
 */

const SAMPLE_DATA = {
  hrms_logo_url: "",
  month: "March",
  month_caps: "MARCH",
  year: "2026",
  month_sh: "Mar",
  year_sh: "26",
  issue_date: "31-03-2026",
  month_days: "31",
  payment_days: "26",
  earnings: "",
  deductions: "",
  compliances_table: "",
  compliance_total: "2,400",
  compliances: "",
  loan_str: "",
  leave_str: "",
  payroll_remarks: "",

  single: {
    TOTAL_PENALTY_DAYS: "0",
    PAYROLL_RUN_DATE: "31-03-2026",
    penalized_day_count: "0",
    MIN_WAGES: "21,000",
    PAYROLL_MONTH: "3",
    PAYROLL_YEAR: "2026",
    PAYROLL_MONTH_YEAR: "March 2026",
    DAYS_IN_MONTH: "31",
    WORKING_DAYS: "26",
    EMP_LEAVES: "1",
    PAYROLL_DAYS: "25",
    ARREAR_DAYS: "0",
    GROSS_SALARY: "75,000",
    NET_SALARY: "62,350",
    PRESENT_DAYS: "25",
    actual_present_days: "25",
    EXTRA_DAYS: "0",
    LWP: "1",
    lwp: "1",
    CREATED_BY: "Admin",
    CREATED_ON: "31-03-2026",
    SALARY_SLIP: "SS-2026-03-1001",
    P_STATUS: "Paid",
    DEDUCTION: "12,650",
    PT: "200",
    TDS: "5,000",
    LWF: "0",
    STATUTORY_BONUS: "0",
    ORIGINAL_LEAVE: "2",
    ABSENCE_DAYS: "1",
    LESS_MIN_WORKS: "0",
    LATE_DAYS: "2",
    EARLY_DAYS: "0",
    HALF_DEDUCT: "0",
    PAYABLE_DAYS: "25",
    WEEKLY_OFF: "4",
    OT: "3,500",
    OT_DAYS: "2",
    EXTRA_OT_AMOUNT: "0",
    EXTRA_OT: "0",
    PASSPORT_NUMBER: "L1234567",
    PAYMENT_TYPE: "Bank Transfer",
    LEAVE_PAY_DAYS: "0",
    LEAVE_PAY_AMOUNT: "0",
    WORKING_HR_IN_A_DAY: "8",
    HOLIDAYS: "1",
    FREEZED_CTC: "12,00,000",
    PAYCUT_AMOUNT: "0",
    EARNED_CTC: "75,000",
    PF_WAGES: "15,000",
    EPF_WAGES: "1,800",
    EPS_WAGES: "1,250",
    EDLI_WAGES: "75",
    ESIC_WAGES: "0",
    PT_WAGES: "200",
    NCP_DAYS: "1",
    ncp_days: "1",
    MISS_DED: "0",
    MISS_EARN: "0",
    LOAN: "5,000",
    ADVANCE: "0",
    ARREAR_AMOUNT: "0",
    IS_REGENERAT_REQUIRED: "No",
    PAID_MONTH_YEAR: "March 2026",
    UPDATED_ON: "31-03-2026",
    YEARLY_FREEZED_CTC: "12,00,000",
    SUB_DEPT_NAME: "Engineering",
    GRADE_NAME: "L4",
    BUSINESS_NAME: "Zimyo Consulting",
    BRANCH_CITY: "Gurugram",
    BRANCH_LOCATION: "Sector 44",
    ZONE_NAME: "North",
    entity_name: "Zimyo Consulting Pvt Ltd",
    emp_code: "ZIM-1001",
    emp_id: "ZIM-1001",
    emp_name: "Rahul Sharma",
    emp_email: "rahul.sharma@zimyo.com",
    email_id: "rahul.sharma@zimyo.com",
    business_unit: "Technology",
    bussiness_code: "TECH",
    joining_date: "15-06-2022",
    mobile_no: "9876543210",
    gender: "Male",
    date_of_birth: "12-05-1994",
    anniversary_date: "",
    last_working_date: "",
    department_name: "Product Engineering",
    designation_name: "Senior Software Engineer",
    location_name: "Gurugram",
    ENFORCE_ESI_TILL: "",
    state_name: "Haryana",
    business_unit_main_name: "Technology",
    ACCOUNT_NUMBER: "XXXX XXXX 4567",
    ACCOUNT_HOLDER_NAME: "Rahul Sharma",
    BANK_NAME: "HDFC Bank",
    ACCOUNT_TYPE: "Savings",
    IFSC_CODE: "HDFC0001234",
    NATIONALITY: "Indian",
    PAN_CARD: "ABCDE1234F",
    pan: "ABCDE1234F",
    AADHAR_CARD: "XXXX XXXX 5678",
    aadhaar_no: "XXXX XXXX 5678",
    UAN_NUMBER: "100876543210",
    uan: "100876543210",
    ESI_NUMBER: "",
    esi: "",
    PF_NUMBER: "HR/GGN/12345/678",
    pf: "HR/GGN/12345/678",
    FATHER_NAME: "Suresh Sharma",
    father_name: "Suresh Sharma",
    EMP_GRADE: "L4",
    SKILL_LEVEL: "Senior",
    ADDRESS: "B-123, Sector 56, Gurugram, Haryana - 122003",
    emp_address: "B-123, Sector 56, Gurugram, Haryana - 122003",
    IBAN_NUMBER: "",
    empDep: "Product Engineering",
    empDes: "Senior Software Engineer",
    empLoc: "Gurugram",
    nationality: "Indian",
    APPLICABLE_FROM: "01-04-2025",
    MONTHLY_CTC: "1,00,000",
    currency_str: "Rupees",
    sub_currency_str: "Paise",
    ABBREVIATION: "INR",
    SYMBOL: "\u20B9",
    financial_year: "2025-26",
    invoice_no: "INV-2026-03-1001",
    workingDays: "26",
    paid_days: "25",
    week_off_plus_holiday: "5",
    lop_present_days: "25",
    gross_array_sum: "75,000",
    scale_array_sum: "1,00,000",
    arrear_array_sum: "0",
    net_deduction_sum: "12,650",
    annual_leave_balance: "8",
    sick_leave_days: "3",
    work_permit: "",
    emp_basic: "30,000",
    total_flexi_amount: "0",
    std_ot_rate: "250",
    wo_ot_rate: "500",
    std_ot: "2",
    wo_ot: "0",
    PAY_CYCLE: "Monthly",
    payable: "62,350",
    amount_in_words: "Sixty Two Thousand Three Hundred Fifty Only",
    PRESENT_COUNT: "25",
    revenue_contribution: "",
    revenue_remarks: "",
    revenue_commission: "",
    ORIGINAL_LEAVE: "2",
  },

  org_details: {
    ORG_NAME: "Zimyo Consulting Pvt Ltd",
    LEGAL_NAME: "Zimyo Consulting Private Limited",
    ENTITY_NAME: "Zimyo Consulting Pvt Ltd",
    ORG_LOGO: "/placeholder-logo.png",
    ORG_ADDRESS: "Plot No. 44, Sector 44",
    ORG_ADDRESS2: "Institutional Area",
    ORG_LOCALITY: "Sector 44",
    ORG_CITY: "Gurugram",
    ORG_STATE: "Haryana",
    ORG_COUNTRY: "India",
    ORG_ZIP_CODE: "122003",
    EMAIL: "hr@zimyo.com",
    MOBILE_NUMBER: "011-4567890",
    PAN: "AABCZ1234F",
    AUTHRISED_SIGNATORY: "Authorized Signatory",
    INCORPORATION_DATE: "01-01-2018",
    ORG_INDUSTRY: "Technology",
    ORG_TYPE: "Private Limited",
    CURRENCY: "INR",
    BANK_NAME: "HDFC Bank",
    BANK_ACC: "XXXX4567",
    BRANCH: "Sector 44",
    CITY: "Gurugram",
    IBAN: "",
    WPS_NUMBER: "",
    MOL_NUMBER: "",
    ot_head: "Overtime",
    extra_ot_head: "Extra Overtime",
    PRODUCT_THEME_COLOR: "#1a73e8",
  },

  new_obj: {
    gross: "75,000",
    deduction: "12,650",
    net_payable: "62,350",
    actual_net_amount: "62,350",
    amount_in_words: "Sixty Two Thousand Three Hundred Fifty Only",
    actual_net_amount_in_words: "Sixty Two Thousand Three Hundred Fifty Only",
    ctc_gross: "1,00,000",
    ctc_deduction: "25,000",
    arrear_gross: "0",
    arrear_deduction: "0",
    arrear_days: "0",
    total_reim_amount: "0",
    gross_without_basic: "45,000",
    yearly_ctc_gross: "12,00,000",
    yearly_ctc_deduction: "3,00,000",
    yearly_net_ctc: "9,00,000",
    has_leave_balance: true,
    tds_plan: "New Regime",
    total_leave_taken: "4",
    total_leave_balance: "8",
    total_loan_recovered: "5,000",
    total_loan_balance: "45,000",
    total_tds_amount: "60,000",
    total_comp: "2,400",
    ytd_sum_err: "7,50,000",
    ytd_sum_ded: "1,26,500",

    earnings: [
      { HEAD_NAME: "Basic", monthly_payable: "30,000", ctc_monthly_payable: "40,000", arrear_monthly_payable: "0", ytd_amt: "3,00,000", yearly_head_amt: "4,80,000", projected_head_amount: "4,80,000", head_exampt_amount: "0", taxable_head_amount: "4,80,000", ABBREVIATION: "INR", SYMBOL: "\u20B9" },
      { HEAD_NAME: "HRA", monthly_payable: "15,000", ctc_monthly_payable: "20,000", arrear_monthly_payable: "0", ytd_amt: "1,50,000", yearly_head_amt: "2,40,000", projected_head_amount: "2,40,000", head_exampt_amount: "1,20,000", taxable_head_amount: "1,20,000", ABBREVIATION: "INR", SYMBOL: "\u20B9" },
      { HEAD_NAME: "Conveyance Allowance", monthly_payable: "1,600", ctc_monthly_payable: "1,600", arrear_monthly_payable: "0", ytd_amt: "16,000", yearly_head_amt: "19,200", projected_head_amount: "19,200", head_exampt_amount: "19,200", taxable_head_amount: "0", ABBREVIATION: "INR", SYMBOL: "\u20B9" },
      { HEAD_NAME: "Special Allowance", monthly_payable: "20,400", ctc_monthly_payable: "28,400", arrear_monthly_payable: "0", ytd_amt: "2,04,000", yearly_head_amt: "3,40,800", projected_head_amount: "3,40,800", head_exampt_amount: "0", taxable_head_amount: "3,40,800", ABBREVIATION: "INR", SYMBOL: "\u20B9" },
      { HEAD_NAME: "Medical Allowance", monthly_payable: "1,250", ctc_monthly_payable: "1,250", arrear_monthly_payable: "0", ytd_amt: "12,500", yearly_head_amt: "15,000", projected_head_amount: "15,000", head_exampt_amount: "15,000", taxable_head_amount: "0", ABBREVIATION: "INR", SYMBOL: "\u20B9" },
      { HEAD_NAME: "LTA", monthly_payable: "6,750", ctc_monthly_payable: "8,750", arrear_monthly_payable: "0", ytd_amt: "67,500", yearly_head_amt: "1,05,000", projected_head_amount: "1,05,000", head_exampt_amount: "0", taxable_head_amount: "1,05,000", ABBREVIATION: "INR", SYMBOL: "\u20B9" },
    ],

    deductions: [
      { HEAD_NAME: "Provident Fund", monthly_payable: "1,800", ctc_monthly_payable: "1,800", arrear_monthly_payable: "0", ytd_amt: "18,000", yearly_head_amt: "21,600", ABBREVIATION: "INR", SYMBOL: "\u20B9" },
      { HEAD_NAME: "Professional Tax", monthly_payable: "200", ctc_monthly_payable: "200", arrear_monthly_payable: "0", ytd_amt: "2,000", yearly_head_amt: "2,400", ABBREVIATION: "INR", SYMBOL: "\u20B9" },
      { HEAD_NAME: "Income Tax (TDS)", monthly_payable: "5,000", ctc_monthly_payable: "5,000", arrear_monthly_payable: "0", ytd_amt: "50,000", yearly_head_amt: "60,000", ABBREVIATION: "INR", SYMBOL: "\u20B9" },
      { HEAD_NAME: "LOP Deduction", monthly_payable: "2,885", ctc_monthly_payable: "0", arrear_monthly_payable: "0", ytd_amt: "2,885", yearly_head_amt: "2,885", ABBREVIATION: "INR", SYMBOL: "\u20B9" },
    ],

    compliance: [
      { HEAD_NAME: "EPF (Employer)", monthly_payable: "1,800", ctc_monthly_payable: "1,800", arrear_monthly_payable: "0", ytd_amt: "18,000", yearly_head_amt: "21,600", ABBREVIATION: "INR", SYMBOL: "\u20B9" },
      { HEAD_NAME: "EPS (Employer)", monthly_payable: "1,250", ctc_monthly_payable: "1,250", arrear_monthly_payable: "0", ytd_amt: "12,500", yearly_head_amt: "15,000", ABBREVIATION: "INR", SYMBOL: "\u20B9" },
      { HEAD_NAME: "EDLI", monthly_payable: "75", ctc_monthly_payable: "75", arrear_monthly_payable: "0", ytd_amt: "750", yearly_head_amt: "900", ABBREVIATION: "INR", SYMBOL: "\u20B9" },
    ],

    reimbursment: [],

    leave_arr: [
      { leave_type: "Casual Leave", leave_taken: "2", leave_balance: "4", leave_opening: "6", new_assigned: "0", previousmonth_balance: "6" },
      { leave_type: "Sick Leave", leave_taken: "1", leave_balance: "3", leave_opening: "4", new_assigned: "0", previousmonth_balance: "4" },
      { leave_type: "Earned Leave", leave_taken: "1", leave_balance: "8", leave_opening: "9", new_assigned: "0", previousmonth_balance: "9" },
    ],

    expenses: [],

    pf_details: [
      { HEAD_NAME: "EPF", pf_ymt: "18,000", payroll_amt: "1,800" },
      { HEAD_NAME: "EPS", pf_ymt: "12,500", payroll_amt: "1,250" },
    ],

    profession_tax: { balance: "200", projected: "2,400", ytd: "2,000" },
    income_tax: { projected: "60,000", ytd: "50,000", balance: "10,000" },
  },

  loan_emi: {
    openong_bal: "50,000",
    emi: "5,000",
    closing_bal: "45,000",
    principle_amount: "4,500",
    interest_amount: "500",
    prerequisite_amount: "0",
  },

  yearly_earning_total: {
    ytd_amount: "7,50,000",
    exempt_amount: "1,54,200",
    taxable_amount: "5,95,800",
    yearly_head_amount: "12,00,000",
    monthly_ctc_amount: "1,00,000",
    projected_amount: "12,00,000",
  },

  detailedOt: {
    hd_ot: "0", hd_ot_amount: "0",
    hd_extra_ot: "0", hd_extra_ot_amount: "0",
    wo_ot: "0", wo_ot_amount: "0",
    wo_extra_ot: "0", wo_extra_ot_amount: "0",
    wd_ot: "2", wd_ot_amount: "3,500",
    wd_extra_ot: "0", wd_extra_ot_amount: "0",
  },

  MISS_HEADS: {
    earning: [],
    deduction: [],
  },
};

module.exports = { SAMPLE_DATA };
